@echo off
set MATLAB=C:\Program Files\MATLAB\R2015a
"%MATLAB%\bin\win64\gmake" -f DP_PMP_MABX_2015a.mk  RSIM_SOLVER_SELECTION=2 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=0"
